#!/usr/bin/env python3
"""TR-268 — type-hint ladder stage 0: the annotated-function score instrument.

ONE command that measures how much of the repo's runtime Python carries type
hints, via a pure AST scan (never imports the scanned code, no subprocesses):

    fn_score  = functions with a return annotation / all functions   (percent)
    arg_score = annotated parameters / all parameters                (percent)

Scope: the repo's runtime modules — scripts/ plus every top-level package dir
(a directory with an __init__.py at the repo root, e.g. task_router/; a src/
layout is covered by the same discovery when present). tests/, data/,
.coding-hermes/ and .gitreins/ are never scanned. Counting rule: EVERY
function and async-function def found by walking each module's AST — nested
defs included, lambdas never, no special-casing of test fixtures or methods.

Regression floor (--floor <pct>): exits 1 when EITHER overall score sits more
than 0.2 percentage points below <pct>. An unreached target never fails —
only a real regression below the achieved level does. The committed baseline
data/tables/type_hint_baseline.jsonl is generated by this very tool (never
hand-typed) and enforced by tests/test_type_hint_floor.py.

Baseline rows with an empty denominator (a module with zero functions or zero
parameters) score 100.0 — vacuously complete. The floor only reads the
_overall row, whose denominators this repo keeps non-empty (asserted in the
floor test).
"""
from __future__ import annotations

import argparse
import ast
import json
import platform
import sys
from datetime import datetime, timezone
from pathlib import Path

#: path components that are never runtime scope, wherever they appear
EXCLUDE_PARTS = {
    "__pycache__", ".git", ".venv", "venv", "node_modules",
    "tests", "data", ".coding-hermes", ".gitreins",
}

#: percentage points of grace below the floor before it bites
FLOOR_GRACE_PP = 0.2

REPO_ROOT = Path(__file__).resolve().parent.parent

EMPTY_DENOMINATOR_SCORE = 100.0


def _is_excluded(rel: Path) -> bool:
    return any(
        part in EXCLUDE_PARTS or part.endswith(".egg-info")
        for part in rel.parts
    )


def discover_scope(root: "str | Path") -> "list[Path]":
    """Runtime .py files under `root`: scripts/ + src/ (when present) plus
    every top-level package dir (a directory with an __init__.py). Sorted by
    repo-relative posix path so output and baselines are stable."""
    root = Path(root).resolve()
    found: "dict[str, Path]" = {}

    def add_dir(d: Path) -> None:
        if not d.is_dir():
            return
        for p in sorted(d.rglob("*.py")):
            rel = p.relative_to(root)
            if not _is_excluded(rel):
                found[rel.as_posix()] = p

    add_dir(root / "scripts")
    add_dir(root / "src")
    for child in sorted(root.iterdir()):
        if not child.is_dir() or child.name.startswith("."):
            continue
        if child.name in ("scripts", "src"):
            continue
        if (child / "__init__.py").is_file():
            add_dir(child)

    return [root / key for key in sorted(found)]


def scan_source(src: str) -> dict:
    """Count functions/annotations in one module's source.

    Raises SyntaxError on unparseable input: a syntax-broken runtime module
    is a loud failure, never a silent zero.
    """
    tree = ast.parse(src)
    functions = 0
    return_annotated = 0
    all_params_annotated = 0
    args = 0
    args_annotated = 0
    for node in ast.walk(tree):
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        functions += 1
        if node.returns is not None:
            return_annotated += 1
        a = node.args
        params = list(a.posonlyargs) + list(a.args) + list(a.kwonlyargs)
        if a.vararg is not None:
            params.append(a.vararg)
        if a.kwarg is not None:
            params.append(a.kwarg)
        n_ann = sum(1 for p in params if p.annotation is not None)
        args += len(params)
        args_annotated += n_ann
        if n_ann == len(params):
            all_params_annotated += 1
    return {
        "functions": functions,
        "return_annotated": return_annotated,
        "all_params_annotated": all_params_annotated,
        "args": args,
        "args_annotated": args_annotated,
    }


def scan_tree(files: "list[Path]", root: "str | Path") -> "dict[str, dict]":
    """Scan every file; keys are repo-relative posix paths (the baseline's
    `module` values)."""
    root = Path(root).resolve()
    counts: "dict[str, dict]" = {}
    for path in files:
        rel = path.resolve().relative_to(root).as_posix()
        counts[rel] = scan_source(path.read_text(encoding="utf-8"))
    return counts


def _pct(num: int, denom: int) -> float:
    if denom == 0:
        return EMPTY_DENOMINATOR_SCORE
    return round(100.0 * num / denom, 4)


def compute_overall(module_counts: "dict[str, dict]") -> dict:
    """Overall totals + fn_score/arg_score (percent, 4 decimals)."""
    totals = {
        "functions": 0, "return_annotated": 0,
        "all_params_annotated": 0, "args": 0, "args_annotated": 0,
    }
    for c in module_counts.values():
        for key in totals:
            totals[key] += c[key]
    overall = dict(totals)
    overall["fn_score"] = _pct(totals["return_annotated"], totals["functions"])
    overall["arg_score"] = _pct(totals["args_annotated"], totals["args"])
    return overall


def with_scores(counts: dict) -> dict:
    row = dict(counts)
    row["fn_score"] = _pct(counts["return_annotated"], counts["functions"])
    row["arg_score"] = _pct(counts["args_annotated"], counts["args"])
    return row


def check_floor(overall: dict, floor: float) -> "tuple[bool, list[str]]":
    """Floor semantics: breach when EITHER score is more than
    FLOOR_GRACE_PP percentage points below `floor`. Returns (ok, failures)."""
    failures = []
    for key in ("fn_score", "arg_score"):
        live = overall[key]
        if live < floor - FLOOR_GRACE_PP:
            failures.append(
                f"{key}: {live:.4f}% is more than {FLOOR_GRACE_PP}pp below "
                f"floor {floor:.4f}%"
            )
    return (not failures, failures)


def render_table(modules: "dict[str, dict]", overall: dict, root: Path,
                 floor: "float | None") -> str:
    lines = []
    head = (f"type-hint score  tool=ast  python={platform.python_version()} "
            f"({platform.python_version_tuple()[0]}.{platform.python_version_tuple()[1]})  "
            f"scope=scripts/ + top-level package dirs, excl tests/ data/ "
            f".coding-hermes/ .gitreins/")
    lines.append(head)
    lines.append(f"root: {root}")
    lines.append("")
    header = (f"{'module':<44} {'fns':>5} {'ret':>5} {'allp':>5} "
              f"{'args':>6} {'ann':>5} {'fn%':>9} {'arg%':>9}")
    lines.append(header)
    lines.append("-" * len(header))
    for mod in sorted(modules):
        c = with_scores(modules[mod])
        lines.append(
            f"{mod:<44} {c['functions']:>5} {c['return_annotated']:>5} "
            f"{c['all_params_annotated']:>5} {c['args']:>6} "
            f"{c['args_annotated']:>5} {c['fn_score']:>9.4f} "
            f"{c['arg_score']:>9.4f}"
        )
    lines.append("-" * len(header))
    lines.append(
        f"{'_overall':<44} {overall['functions']:>5} "
        f"{overall['return_annotated']:>5} "
        f"{overall['all_params_annotated']:>5} {overall['args']:>6} "
        f"{overall['args_annotated']:>5} {overall['fn_score']:>9.4f} "
        f"{overall['arg_score']:>9.4f}"
    )
    if floor is not None:
        ok, failures = check_floor(overall, floor)
        lines.append("")
        if ok:
            lines.append(
                f"floor {floor:.4f}%: OK (both scores within "
                f"{FLOOR_GRACE_PP}pp of or above the floor)"
            )
        else:
            for f in failures:
                lines.append(f"floor {floor:.4f}%: BREACH — {f}")
    return "\n".join(lines)


def build_json(modules: "dict[str, dict]", overall: dict,
               floor: "float | None") -> dict:
    doc = {
        "tool": "ast",
        "python": (f"{platform.python_version_tuple()[0]}."
                   f"{platform.python_version_tuple()[1]}"),
        "python_full": platform.python_version(),
        "measured_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "modules": [
            {"module": mod, **with_scores(modules[mod])}
            for mod in sorted(modules)
        ],
        "overall": {"module": "_overall", **overall},
    }
    if floor is not None:
        ok, failures = check_floor(overall, floor)
        doc["floor"] = floor
        doc["floor_ok"] = ok
        doc["floor_failures"] = failures
    return doc


def main(argv: "list[str] | None" = None) -> int:
    parser = argparse.ArgumentParser(
        description="TR-268 type-hint score instrument (AST scan)."
    )
    parser.add_argument(
        "--floor", type=float, default=None, metavar="PCT",
        help="regression floor in percent: exit 1 when either overall score "
             f"is more than {FLOOR_GRACE_PP}pp below PCT",
    )
    parser.add_argument(
        "--json", action="store_true", help="machine-readable JSON output",
    )
    args = parser.parse_args(argv)

    root = REPO_ROOT
    files = discover_scope(root)
    if not files:
        print("ERROR: scope discovery found no runtime modules", file=sys.stderr)
        return 2
    modules = scan_tree(files, root)
    overall = compute_overall(modules)

    if args.json:
        print(json.dumps(build_json(modules, overall, args.floor), indent=2))
    else:
        print(render_table(modules, overall, root, args.floor))

    if args.floor is not None:
        ok, _ = check_floor(overall, args.floor)
        return 0 if ok else 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
